from __future__ import annotations

from html import escape
import json
from pathlib import Path

import pytest

from fedleave.commands.data import import_wms_http
from fedleave.config import init_config
from fedleave.storage import write_json
from fedleave.wms_import import WmsImportError, parse_wms_http_leave_report


def _row(cells: list[str]) -> str:
    return "<tr>" + "".join(f"<td>{escape(value)}</td>" for value in cells) + "</tr>"


def _data_row(*, date: str, code: str, start_time: str, hours: str, status: str = "", total: str = "") -> str:
    cells = [""] * 38
    cells[13] = date
    cells[15] = code
    cells[17] = "300000205824"
    cells[19] = "2000"
    cells[21] = date
    cells[23] = start_time
    cells[25] = hours
    cells[27] = total
    cells[29] = "0700"
    cells[31] = status
    cells[33] = "( )-Yes ( )-No"
    return _row(cells)


def _wms_html(body_rows: list[str], *, start: str = "11-Jan-2026", end: str = "09-Jul-2026") -> str:
    return (
        "<html><body>"
        '<table class="jrPage">'
        + _row(["", "Clocking Report", ""])
        + _row(["", "Date:", "", f"{start} - {end}", "", "Generated By:", "Joshua L Guthrie", ""])
        + _row(["", "Clocking Team/User:", "", "Joshua L Guthrie", ""])
        + "".join(body_rows)
        + "</table></body></html>"
    )


def test_parse_wms_http_leave_report_extracts_transactions() -> None:
    report = parse_wms_http_leave_report(
        _wms_html(
            [
                _data_row(date="12-Jan-2026", code="RG", start_time="7.00", hours="4.50"),
                _data_row(date="13-Jan-2026", code="LA", start_time="7.00", hours="3.00"),
                _data_row(date="13-Jan-2026", code="LS/DD", start_time="10.00", hours="1.50", status="Incomplete Clocking"),
                _data_row(date="13-Jan-2026", code="CD", start_time="15.50", hours="1.00", total="9.0"),
            ]
        )
    )

    assert report.leave_year == 2026
    assert report.leave_year_start == "2026-01-11"
    assert report.leave_year_end == "2026-07-09"
    assert report.generated_by == "Joshua L Guthrie"
    assert len(report.specs) == 3
    assert report.ignored_rows == 1

    assert [(spec.date, spec.category, spec.direction, spec.hours) for spec in report.specs] == [
        ("2026-01-13", "annual", "used", 3.0),
        ("2026-01-13", "sick", "used", 1.5),
        ("2026-01-13", "credit", "earned", 1.0),
    ]
    assert "Incomplete Clocking" in report.specs[1].description
    assert "start 10:00" in report.specs[1].description


def test_parse_wms_http_leave_report_rejects_unknown_codes() -> None:
    with pytest.raises(WmsImportError, match="Unsupported WMS leave code ZZ"):
        parse_wms_http_leave_report(
            _wms_html([
                _data_row(date="13-Jan-2026", code="ZZ", start_time="7.00", hours="1.00"),
            ])
        )


def test_import_wms_http_creates_missing_leave_year(tmp_path: Path) -> None:
    data_dir = tmp_path / "data"
    report_file = tmp_path / "clocking.html"
    report_file.write_text(
        _wms_html(
            [
                _data_row(date="13-Jan-2026", code="LA", start_time="7.00", hours="3.00"),
                _data_row(date="13-Jan-2026", code="CD", start_time="15.50", hours="1.00"),
            ]
        ),
        encoding="utf-8",
    )

    import_wms_http(input=report_file, data_dir=data_dir)

    year_file = data_dir / "leave_years" / "2026.json"
    imported = json.loads(year_file.read_text(encoding="utf-8"))
    assert imported["leave_year"] == 2026
    assert imported["leave_year_start"] == "2026-01-11"
    assert imported["starting_balances"]["annual"] == 0.0
    assert any(
        tx["date"] == "2026-01-13" and tx["category"] == "annual" and tx["direction"] == "used" and tx["source"] == "wms-http"
        for tx in imported["transactions"]
    )
    assert any(
        tx["date"] == "2026-01-13" and tx["category"] == "credit" and tx["direction"] == "earned" and tx["source"] == "wms-http"
        for tx in imported["transactions"]
    )


def test_import_wms_http_overwrites_matching_transactions(tmp_path: Path) -> None:
    data_dir = tmp_path / "data"
    report_file = tmp_path / "clocking.html"
    report_file.write_text(
        _wms_html(
            [
                _data_row(date="13-Jan-2026", code="LA", start_time="7.00", hours="3.00"),
                _data_row(date="13-Jan-2026", code="LS", start_time="10.00", hours="1.50"),
            ]
        ),
        encoding="utf-8",
    )
    init_config(
        year=2026,
        leave_year_start="2026-01-11",
        annual_accrual=6.0,
        starting_balances={
            "annual": 120.0,
            "sick": 180.0,
            "comp": 0.0,
            "credit": 0.0,
            "travel_comp": 0.0,
            "time_off_award": 0.0,
            "religious_comp": 0.0,
            "restored_annual": 0.0,
        },
        data_dir=data_dir,
    )

    year_file = data_dir / "leave_years" / "2026.json"
    leave_year = json.loads(year_file.read_text(encoding="utf-8"))
    leave_year["transactions"].append(
        {
            "id": "20260113-999",
            "date": "2026-01-13",
            "category": "annual",
            "direction": "used",
            "hours": 8.0,
            "description": "Old manual entry",
            "status": "planned",
            "source": "manual",
            "created_at": "2026-01-13T00:00:00",
            "updated_at": "2026-01-13T00:00:00",
        }
    )
    write_json(year_file, leave_year)

    import_wms_http(input=report_file, data_dir=data_dir)

    imported = json.loads(year_file.read_text(encoding="utf-8"))
    assert not any(tx["id"] == "20260113-999" for tx in imported["transactions"])
    assert any(
        tx["date"] == "2026-01-13"
        and tx["category"] == "annual"
        and tx["direction"] == "used"
        and tx["hours"] == 3.0
        and tx["source"] == "wms-http"
        for tx in imported["transactions"]
    )
    assert any(
        tx["date"] == "2026-01-13"
        and tx["category"] == "sick"
        and tx["direction"] == "used"
        and tx["hours"] == 1.5
        and tx["source"] == "wms-http"
        for tx in imported["transactions"]
    )
